title: "Elon Musk Book Recommendations"
description: "Books recommended by Elon Musk, with original quotes and tweet links."
theme: minima
baseurl: "/books-recommended-by-elon-musk"

collections:
  books:
    output: true
    permalink: /books/:name

defaults:
  - scope:
      path: ""
      type: books
    values:
      layout: book
      cover: ""
      author: ""
      year: ""
      quote: ""
      source: ""
      summary: ""

include:
  - assets

plugins:
  - jekyll-seo-tag
