title: "Elon Musk Book Recommendations"
description: "Books recommended by Elon Musk, with original quotes and tweet links."
theme: minima
baseurl: "/books-recommended-by-elon-musk"

collections:
  books:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"

include:
  - assets

exclude:
  - README.md
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - .github

plugins:
  - jekyll-seo-tag
